### ISSUE TITLE
New Papertrail CA bundle next week

### ISSUE THREAD

**Issue by markdascher** [azavea/ansible-papertrail#13]
Papertrail will be updating **papertrail-bundle.pem** on **Tuesday, May 15**. The new SHA-256 checksum will be `79ea479e9f329de7075c40154c591b51eb056d458bc4dff76d9a4b9c6c4f6d0b`, but given that we might continue updating this file from time to time, I'd recommend against simply hard-coding a new checksum. Instead, either omit the checksum entirely, or embed the entire bundle rather than downloading it. Either option ensures that Papertrail is free to update the source without breaking anyone's deployment.

**Comment by hectcastro** [comment]
Hey @markdascher, the 1.3.0 release of this role supports overriding the PEM SHA. Do you have a link to an announcement or something that references the new SHA? I haven't been able to find one.

**Comment by markdascher** [comment]
Thanks @hectcastro! This is the only announcement at the moment, other than similar messages on other dependent repositories. Once the new file is updated, we'll also update the docs at https://help.papertrailapp.com/kb/configuration/encrypting-remote-syslog-with-tls-ssl/ to include the new checksums, as well as guidance to expect the checksum to change periodically.
