### ISSUE TITLE
DEPRECATION WARNING

### ISSUE THREAD

**Issue by mikegleasonjr** [azavea/ansible-papertrail#5]
I received this while installing your role with ansible 2:

> [DEPRECATION WARNING]: The comma separated role spec format, use the yaml/explicit format instead.. This feature will be removed in a future release. Deprecation warnings can be disabled by
setting deprecation_warnings=False in ansible.cfg.

**Comment by hectcastro** [comment]
Do you have any additional detail around how you executed the role so that I can attempt to reproduce locally? Directly via `ansible-playbook`? Via some wrapper tool (Packer, Vagrant)?

**Comment by briandbecker** [comment]
I don't think this is a problem with the role itself but perhaps the way you are including the role. See https://github.com/ansible/ansible/pull/14612 and https://github.com/mscherer/ansible/blob/fix_spurious_warning/lib/ansible/playbook/role/requirement.py#L76

**Comment by hectcastro** [comment]
Ah, just to confirm my understanding, something like `python_development` below is deprecated usage?

```yaml
dependencies:
  - { role: "azavea.python", python_development: True }
```

**Comment by briandbecker** [comment]
You can see here the old style and new stile a few lines further down: https://github.com/mscherer/ansible/blob/fix_spurious_warning/lib/ansible/playbook/role/requirement.py#L147

**Comment by hectcastro** [comment]
@mikegleasonjr Going to close, but feel free to reopen if you determine these findings are incorrect.

**Comment by mikegleasonjr** [comment]
I just re-installed this role. I added the line `- src: azavea.papertrail` to my `requirements.yml` then...

`ansible-galaxy install -r requirements.yml -p .`

And the warning showed up like this:

```
[...]
- downloading role 'papertrail', owned by azavea
- downloading role from https://github.com/azavea/ansible-papertrail/archive/1.1.2.tar.gz
- extracting azavea.papertrail to ./azavea.papertrail
- azavea.papertrail was installed successfully
[DEPRECATION WARNING]: The comma separated role spec format, use the yaml/explicit format instead..
This feature will be removed in a future release. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.
- dependency azavea.papertrail is already installed, skipping.
```

Notice somehow the role tries to install a second time...
